apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  namespace: todolist-app
  labels:
    type: local
spec:
  storageClassName: longhorn
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

