apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: todolist-app
spec:
  storageClassName: standard-ssd-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi