apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: todolist-app
spec:
  storageClassName: standard-ssd-default
  request:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce

